### ISSUE TITLE
Outdated

### ISSUE THREAD

**Issue by RyudoGaming** [SheepGoMeh/SideHUD#5]
By the looks of it, with no updates for 5 months I will assume that this has been abandoned, but if not, an update to work with the new version of XIV launcher would be fabulous. 
![image](https://user-images.githubusercontent.com/39316798/136692818-e955fc10-bf76-44b5-878b-d34079934ce7.png)

**Comment by bbeenn1** [comment]
I don't know how involved it would be to update this to work with the new system, otherwise I would take a crack at updating it since I really liked this hud as it kept everything I needed to monitor near my character.
